
export {default as Signup} from './Signup'
export {default as Login} from './Login'
export {default as WelcomePage} from './WelcomPage'
export {default as WalkTroughPageOne} from './WalkTroughPageOne'
export {default as WalkTroughPageTwo} from './WalkTroughPageTwo'
export {default as WalkTroughPageThree} from './WalkTroughPageThree'
export {default as ValidationPage} from './ValidationPage'
export {default as ForgotPassword} from './ForgotPassword'
export {default as ResetPassword} from './ResetPassword'
export {default as Rides} from './Rides'
export {default as RegisterDriver} from './RegisterDriver'
export {default as DriverSetting} from './driver/DriverSetting'